# Generated by Django 4.0.6 on 2022-10-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('salary', models.IntegerField()),
                ('designation', models.CharField(max_length=70)),
                ('company', models.CharField(max_length=70)),
            ],
        ),
    ]
