# Generated by Django 4.0.6 on 2022-10-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.CharField(max_length=70),
        ),
    ]
