# Generated by Django 4.0.6 on 2022-10-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_alter_user_salary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='employee',
        ),
    ]
